// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func BottomSheet() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/static/bottomSheet.js\"></script><template id=\"bottom-sheet-template\"><div aria-hidden=\"true\" class=\"dvh peer aria-hidden:hidden transition-transform fixed bottom-0 left-0 right-0 translate-y-full aria-expanded:translate-y-0 z-50\"><div class=\"bg-gray-300 rounded-t-lg absolute inset-0 h-dvh -z-10\"></div><div class=\"grabber w-full h-6 flex justify-center items-center\"><div class=\"w-20 bg-gray-400 rounded-full h-1\"></div></div><div class=\"modal-body\"></div></div><div class=\"scrim fixed inset-0 bg-black opacity-0 transition-all peer-aria-expanded:opacity-30 peer-aria-hidden:hidden z-40\"></div></template>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
